name: Dependabot

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  dependabot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Dependabot
        uses: dependabot/dependabot-core@v0.159.3
        with:
          directory: "/"
          target-branch: "main"
          package-manager: "pip"
          allow:
            - dependency-type: "direct"
            - dependency-name: "django"
          ignore:
            - dependency-name: "pytest"
            - dependency-name: "coverage"
